export const ADD_CART_LIST_COUNT = 'addCartListCount'
export const PUSH_CART_LIST = 'pushCartList'
export const CART_IS_SELECT = 'cartIsSelect'
export const CART_CHECK_ALL_SELECT = 'cartCheckAllSelect'
export const CART_IS_CHECK_ALL = 'cartIsCheckAll'
export const CART_UN_CHECK_ALL = 'cartUnCheckAll'
export const UPDATE_CART_TOTAL_PRICE = 'updateCartTotalPrice'
export const UPDATE_CART_SELECT = 'updateCartSelect'
